{{- if and .Values.nodeAgent.enabled .Values.kubescapeStorage.enabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.nodeAgent.ClusterRole }}
  namespace: {{ .Values.nodeAgent.Namespace }}
rules:
- apiGroups: ["v1", "apps/v1", "batch/v1"]
  resources: ["pods", "nodes", "deployments", "daemonsets", "statefulsets", "jobs", "cronjobs", "replicasets"]
  verbs: ["get"]
- apiGroups: ["v1"]
  resources: ["pods"]
  verbs: ["watch"]
- apiGroups: ["*"]
  resources: ["sbomspdxv2p3"]
  verbs: ["create", "get", "update"]
{{- end}}