{{- if and .Values.nodeAgent.enabled .Values.kubescapeStorage.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nodeAgent.ConfigMap }}
  namespace: {{ .Values.nodeAgent.Namespace }}
data:
  SneefferConfigurationFile.txt: |
  {
      "sniffer": {
          "services": [
              {
                  "Name": "relevantCVEs"
              }
          ],
          "maxSniffingTimePerContainer": {{ .Values.nodeAgent.ConfigMap.maxSniffingTime }}
      },
      "falcoEbpfEngine": {
          "kernelObjPath": "/etc/node-agent/resources/ebpf/falco/kernel_obj.o",
          "ebpfEngineLoaderPath": "/etc/node-agent/resources/ebpf/falco/userspace_app"
      },
      "node": {
          "name": "minikube"
      },
      "db": {
          "updateDataPeriod": 30
      },
      "clusterName": {{ .Values.clusterName }}
  }
{{- end}}