{{- if and .Values.nodeAgent.enabled .Values.kubescapeStorage.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.daemonset.name }}
  namespace: {{ .Values.nodeAgentNamespace }}
  labels: 
      app: {{ .Values.daemonset.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.daemonset.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.daemonset.name }}
        alt-name: {{ .Values.daemonset.name }}
    spec:
      serviceAccountName: {{ .Values.nodeAgentServiceAccount }}
      automountServiceAccountToken: {{ .Values.daemonset.automountServiceAccountToken }}
      volumes:
        {{- range .Values.daemonset.volumes }}
        - name: {{ .name }}
        {{- if .configMap}}
          configMap: 
            name: {{ .configMap.name }}
        {{ else if .emptyDir }}
          emptyDir: {}
        {{ else if .hostPath }}
          hostPath:
            path: {{ .hostPath.path }}
            type: {{ .hostPath.type }}
        {{- end }}      
        {{- end }}      
      initContainers:
      - env:
        {{- range .Values.daemonset.initContainer.env }}
        - name: {{ .name  }}
        {{- if .value }}
          value: "{{ .value }}"
        {{- end }}
        {{- end }}
        image: "{{ .Values.daemonset.initContainer.image.repository }}:{{ .Values.daemonset.initContainer.image.tag }}"
        imagePullPolicy: {{ .Values.daemonset.initContainer.image.pullPolicy }}
        name: {{ .Values.daemonset.initContainer.name }}
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        {{- range .Values.daemonset.initContainer.volumeMounts }}
        - mountPath: {{ .mountPath }}
          name: {{ .name }}
          readOnly: {{ .readOnly }}
        {{- end }}
      containers:
        - name: {{ .Values.daemonset.containers.nodeAgent.name }}
          image: "{{ .Values.daemonset.containers.nodeAgent.image.repository }}:{{ .Values.daemonset.containers.nodeAgent.image.tag }}"
          imagePullPolicy: {{ .Values.daemonset.containers.nodeAgent.image.pullPolicy }}
          env:
            - name: myNode
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{- range .Values.daemonset.containers.nodeAgent.env }}
            - name: {{ .name  }}
            {{- if .value }}
              value: "{{ .value }}"
            {{- end }}
            {{- end }}
          securityContext:
            runAsUser: {{ .Values.daemonset.containers.nodeAgent.securityContext.user }}
            capabilities:
              add: 
                {{- range .Values.daemonset.containers.nodeAgent.securityContext.capabilities.add }}
                - {{ .name }}
                {{- end }}
          volumeMounts:
          {{- range .Values.daemonset.containers.nodeAgent.volumeMounts }}
          - mountPath: {{ .mountPath }}
            name: {{ .name }}
          {{- end }}
{{- end}}